name: streamlit-automl
channels:
  - snowflake
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - snowflake-ml-python==1.4.0
  - streamlit==1.35.0
  - python-dotenv
  - numpy==1.26.3
  - xgboost==1.7.3
  - scikit-learn==1.3.0
  - black==24.4.2
  - nbformat==5.10.4
  - nbconvert==7.16.4
